stages:
  - test
  - build
  - push

test:
  stage: test
  image: python:3.10.10
  script:
    - pip install -r requirements.txt
    - python manage.py test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t abdelrhmanawidaa/graduation-app:latest .

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push abdelrhmanawidaa/graduation-app:latest
  only:
    - main